pipeline {
    agent {
        docker {
            image 'maven:3-alpine' 
            args '-v /root/.m2:/root/.m2' 
        }
    }
    stages {
        stage('Build') { 
            steps {
                sh 'mvn -B -DskipTests clean package' 
		sh 'gcc -o teste teste.c'
            }
        }
	stage('Test') {
            steps {
                sh 'mvn test'
		sh './teste'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
	}
	stage('Deliver') {
            steps {
                sh 'scripts/deliver.sh'
            }
        }
    }
}