pipeline {
    agent {
        docker {
            image 'maven:3-alpine' 
            args '-v /root/.m2:/root/.m2' 
        }
    }
    stages {
        stage('Build') { 
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
	stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
	}
	stage('Deliver') {
            steps {
		script {
                    def opc
                    def val1
                    def val2

                    def userInput = input(
                            id: 'userInput', message: 'Calculadora',
                            parameters: [
                                    string(description: 'Operação',
                                            name: 'Config'),
                                    string(description: 'Valor 1',
                                            name: 'Valor1'),
                                    string(description: 'Valor 2',
                                            name: 'Valor2'),
                            ])
                    opc = userInput.Config?:''
                    val1 = userInput.Valor1?:''
                    val2 = userInput.Valor2?:''
		}
                sh 'jenkins/scripts/deliver.sh ${opc} ${val1} ${val2}'
            }
        }
    }
}